apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: query-internal-qualification
  name: query-internal-qualification
spec:
  replicas: 1
  selector:
    app: query-internal-qualification
    deploymentconfig: query-internal-qualification
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: query-internal-qualification
        deploymentconfig: query-internal-qualification
    spec:
      containers:
        - name: query-internal-qualification
          image: image-registry.openshift-image-registry.svc:5000/internal-qualification/query-internal-qualification:latest
          env:
            - name: SPRING_APPLICATION_JSON
              value: '{"server":{"undertow":{"io-threads":10, "worker-threads":80 }}}'
            - name: JAVA_OPTIONS
              value: '-Xms640m -Xmx1024m -Dfile.encoding=ISO-8859-1'
          envFrom:
            - configMapRef:
                name: configmap-query-internal-qualification
            - secretRef:
                name: secret-query-internal-qualification
          readinessProbe:
            httpGet:
              path: /telefonica/customer/v1/queryQualification/
              port: 8080
              scheme: HTTP
            failureThreshold: 3
            initialDelaySeconds: 80
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 120
          livenessProbe:
            httpGet:
              path: /telefonica/customer/v1/queryQualification/
              port: 8080
              scheme: HTTP
            failureThreshold: 2
            initialDelaySeconds: 80
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 120
          resources:
            limits:
              cpu: 512m
              memory: 1Gi
            requests:
              cpu: 512m
              memory: 1Gi