apiVersion: v1
kind: Secret
metadata:
  name: secret-query-internal-qualification
type: Opaque
data:
  spring.datasource.username: aW50LXF1YWwtdXNlcg==
  spring.datasource.password: aW50LXF1YWwtdXNlcg==